Albumapp/urls.py
from functools import partial
from django.urls import path, include
from .import views

app_name = 'Albumapp'

urlpatterns = [
     path('', views.albumspage, name = 'albumspage'),
     path('view_photo/', views.view_photo, name = 'view_photo'),
     path('create_album/', views.create_album, name = 'create_album'),
     path('edit/', views.edit_album, name = 'edit_album'),
     path('all_photos/', views.view_all_photo, name = 'all_photos'),
     path('about/', views.about_us, name = 'about')
]

Image_cloud/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Albumapp.urls', namespace='Albumapp')),
    path('account/', include('sign_up_app.urls', namespace='sign_up_app'))
]


 
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

sign_up_app/urls.py
from functools import partial
from django.urls import path, include
from .import views

app_name = 'sign_up_app'

urlpatterns = [
     path('signup/', views.signup, name = 'signup'),
     path('login/', views.login_user, name = 'login'),
     path('logout/', views.logout_user, name = 'logout'),
     path('profile/', views.profile, name = 'profile'),
     path('change_profile/', views.change_profile, name = 'change_profile'),
     path('password/', views.change_pass, name = 'change_password')
     
]

Albumapp/models.py
from django.db import models

# Create your models here.

class Albums(models.Model):
    thumbnail = models.ImageField(upload_to = 'album/images/')
    title = models.CharField(max_length=400)
    discription = models.TextField()
    creation = models.DateTimeField(auto_now_add=True)

    #def __str__(self):
    #    return self.title


class Images(models.Model):
    thumbnail = models.ImageField(upload_to = 'album/images/')
    discription = models.TextField()
    creation = models.DateTimeField(auto_now_add=True)

sign_up_app/models.py
from django.db import models

# Create your models here.

Albumapp/forms.py
from django import forms
from django.core import validators
from .import models


class CreateAlbum(forms.ModelForm):
    class Meta:
        model = models.Albums
        fields = "__all__"

sign_up_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from django.forms import fields

class SignupForm(UserCreationForm):
    email = forms.EmailField(required=True)
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class ProfileChangeForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'password')

Albumapp/views.py
from django.shortcuts import render
from .models import Albums, Images
from Albumapp import forms
# Create your views here.

def albumspage(request):
    albums = Albums.objects.all()
    context = {
        'albums':albums

    }
    return render(request, 'album/albums.html', context)

    

def create_album(request):
    create_form = forms.CreateAlbum()

    if request.method == 'POST':

        create_form = forms.CreateAlbum(request.POST)

        if create_form.is_valid():
            create_form.save(commit = True)
            return albumspage(request)


    dict = {
        'massage':'success',
        'create_form':create_form
    }

    return render(request, 'album/forms.html', context=dict)





def view_photo(request):
    images = Images.objects.all()

    context = {
        'images':images
    }
    return render(request, 'album/view_photo.html', context)


def view_all_photo(request):

    context = {
    }
    return render(request, 'album/view_all_photo.html', context)


def edit_album(request):

    context = {

    }
    return render(request, 'album/edit_album.html', context)


def about_us(request):
    context = {
        'images':'about us'
    }
    return render(request, 'album/about_us.html', context)

sign_up_app/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm
from django.contrib.auth import authenticate,logout,login
from django.shortcuts import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from sign_up_app.forms import SignupForm, ProfileChangeForm

def signup(request):
    form = SignupForm()
    register = False
    
    
    if request.method == 'POST':
        form = SignupForm(data=request.POST)
        if form.is_valid():
            form.save()
            register = True

    context ={
        'title':'Create Account From',
        'signup_form':form,
        'register':register
    }
    return render(request, 'account/signup.html', context)


def login_user(request):
    login_form = AuthenticationForm()
    if request.method == 'POST':
        login_form = AuthenticationForm(data=request.POST)
        if login_form.is_valid():
            username = login_form.cleaned_data.get('username')
            password = login_form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse('Albumapp:albumspage'))
    return render(request, 'account/login.html', context={'login_form':login_form})

@login_required
def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('Albumapp:albumspage'))
            
@login_required
def profile(request):
    return render(request, 'account/profile.html', context={})


@login_required
def change_profile(request):
    curr_user = request.user
    change_form = ProfileChangeForm(instance=curr_user)
    if request.method == 'POST':
        change_form = ProfileChangeForm(request.POST, instance=curr_user)
        if change_form.is_valid():
            change_form.save()
            change_form = ProfileChangeForm(instance=curr_user)

    return render(request, 'account/change_profile.html', context={'change_form':change_form})


@login_required
def change_pass(request):
    curr_user = request.user
    changed = False
    change_pass_form = PasswordChangeForm(curr_user)
    if request.method == 'POST':
        change_pass_form = PasswordChangeForm(curr_user, data=request.POST)
        if change_pass_form.is_valid():
            change_pass_form.save()
            changed = True
            return HttpResponseRedirect(reverse('Albumapp:albumspage'))
    return render(request, 'account/change_pass.html', context={'change_pass_form':change_pass_form, 'changed':changed})

templates/album/about_us.html
{% extends "navbar.html" %}
{% block title_block %} About us {% endblock %}
{% block body_block %}
{% load crispy_forms_tags %}

<main>

  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">About Us</h1>
        <p class="lead text-muted">
            Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
        </p>
      </div>
    </div>
  </section>

</main>

{% endblock %}

templates/album/albums.html
{% extends "navbar.html" %}
{% block title_block %} Albums {% endblock %}
{% block body_block %}
{% load crispy_forms_tags %}

<main>

  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">Welcome to Image Cloud</h1>
        <p class="lead text-muted">'Image Cloud' is a collective endeavour of thousands of passionate photographers led by Image Cloud team, You can upload here all of your photo forever</p>
        <p>
          <a href="{% url 'Albumapp:create_album' %}" class="btn btn-primary my-2">Create an Album</a>
        </p>
      </div>
    </div>
  </section>

  <div class="album py-5 bg-light">
    <div class="container">

      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">

        {% for album in albums %}
        <div class="col">
          <div class="card shadow-sm">
            <img class="bd-placeholder-img card-img-top" width="100%" height="225" src="{{ album.thumbnail.url }}" alt="image">

            <div class="card-body">
              <p class="card-text">Album of: {{ album.title }}</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <button type="button" class="btn btn-sm btn-outline-secondary"><a href="{% url 'Albumapp:view_photo' %}">View Photo</a></button>
                  <button type="button" class="btn btn-sm btn-outline-secondary"><a href="{% url 'Albumapp:edit_album' %}">Edit Album</a></button>
                </div>
                <small class="text-muted">{{ album.creation | timesince }}</small>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}

      </div>
    </div>
  </div>

</main>

{% endblock %}

templates/album/edit_album.html
{% extends "navbar.html" %}
{% block title_block %} Edit Album {% endblock %}
{% block body_block %}
{% load crispy_forms_tags %}
<main>

  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">Make change to your album</h1>
      </div>
    </div>
  </section>

  <div class="album py-5 bg-light">
    <div class="container">

      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">

        {% for image in images %}
        <div class="col">
          <div class="card shadow-sm">
           
            <img width="100%" height="225" src="{{ album.thumbnail.url }}" alt="image" class="img-thumbnail">

            <div class="card-body">
              <p class="card-text">Album of: {{ image.title }}</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <button type="button" class="btn btn-sm btn-outline-secondary"><a href="{% url 'Albumapp:view_photo' %}">View Photo</a></button>
                  <button type="button" class="btn btn-sm btn-outline-secondary"><a href="{% url 'Albumapp:edit_album' %}">Edit Album</a></button>
                </div>
                <small class="text-muted">{{ image.creation | timesince }}</small>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}

      </div>
    </div>
  </div>

</main>

{% endblock %}

templates/album/forms.html
{% extends "navbar.html" %}
{% block title_block %} Form {% endblock %}
{% block body_block %}
{% load crispy_forms_tags %}
<main>

  <section class="py-6 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">Create your album</h1>
      
      </div>
    </div>
  </section>

  <div class="album py-6 bg-light">
    <div class="container">

        <form class="form-control" id="formGroupExampleInput2" method="POST">

            <!-- new nav end -->
            {{ create_form.as_p }}
            {% csrf_token %}
            <input type="submit" name='submit' vlue='add' class='btn btn-primary'>
            
        </form>
      </div>
    </div>
  </div>

</main>


{% endblock %}

templates/album/view_all_photo.html
{% extends "navbar.html" %}
{% block title_block %} View Photos {% endblock %}
{% block body_block %}
{% load crispy_forms_tags %}
<main>

  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">All photo here</h1>
      </div>
    </div>
  </section>

  <div class="album py-5 bg-light">
    <div class="container">

      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">

        {% for image in images %}
        <div class="col">
          <div class="card shadow-sm">
           
            <img width="100%" height="225" src="{{ image.thumbnail.url }}" alt="image" class="img-thumbnail">

            <div class="card-body">
              <p class="card-text">Album of: {{ image.title }}</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <button type="button" class="btn btn-sm btn-outline-secondary"><a href="{% url 'Albumapp:view_photo' %}">View Photo</a></button>
                  <button type="button" class="btn btn-sm btn-outline-secondary"><a href="{% url 'Albumapp:edit_album' %}">Edit Album</a></button>
                </div>
                <small class="text-muted">{{ image.creation | timesince }}</small>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}

      </div>
    </div>
  </div>

</main>

{% endblock %}

templates/album/view_photo.html
{% extends "navbar.html" %}
{% block title_block %} View Photo {% endblock %}
{% block body_block %}
{% load crispy_forms_tags %}
<main>

  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">All of this albums</h1>
      </div>
    </div>
  </section>

  <div class="album py-5 bg-light">
    <div class="container">

      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
<!-- end new card -->
        {% for image in images %}
        <div class="col">
          <div class="card shadow-sm">
           
            <img width="100%" height="225" src="{{ album.thumbnail.url }}" alt="image" class="img-thumbnail">

            <div class="card-body">
              <p class="card-text">Album of: {{ image.title }}</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <button type="button" class="btn btn-sm btn-outline-secondary"><a href="{% url 'Albumapp:view_photo' %}">View Photo</a></button>
                  <button type="button" class="btn btn-sm btn-outline-secondary"><a href="{% url 'Albumapp:edit_album' %}">Edit Album</a></button>
                </div>
                <small class="text-muted">{{ image.creation | timesince }}</small>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}

      </div>
    </div>
  </div>

</main>

{% endblock %}

templates/navbar.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.83.1">
    <title>{{title}}</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/album/">

    

    <!-- Bootstrap core CSS -->
<link href="{% static 'assets/dist/css/bootstrap.min.css' %}" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    
  </head>
  <body>
    
<header>

<!-- new nav start -->
<div class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light rounded" aria-label="Eleventh navbar example">
      <div class="container-fluid">
        {% if user.is_authenticated %}
        <a class="navbar-brand" href="{% url 'sign_up_app:profile' %}">Profile</a>
        {% else %}
        <a class="navbar-brand" href="{% url 'Albumapp:albumspage' %}">Profile</a>
        {% endif %}

        <div class="collapse navbar-collapse" id="navbarsExample09">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'Albumapp:albumspage' %}">Home</a>
            </li>

            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="dropdown09" data-bs-toggle="dropdown" aria-expanded="false">Control Account</a>
              <ul class="dropdown-menu" aria-labelledby="dropdown09">
                {% if user.is_authenticated %}
                <li><a class="dropdown-item" href="{% url 'sign_up_app:logout' %}">Logout</a></li>
                
                {% else %}
                <li><a class="dropdown-item" href="{% url 'sign_up_app:signup' %}">Sign-in</a></li>
                <li><a class="dropdown-item" href="{% url 'sign_up_app:login' %}">Log-in</a></li>
                {% endif %}
                <li><a class="dropdown-item" href="{% url 'Albumapp:about' %}">About us</a></li>
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <div>

<!-- new nav end -->
  

</header>

{% block body_block %}

{% endblock %}

<footer class="text-muted py-5">
  <div class="container">
    <p class="float-end mb-1">
      <a href="#">Back to top</a>
    </p>
    <p class="mb-1">Thanks to be here!!</p>
  </div>
</footer>


    <script src="{% static 'assets/dist/js/bootstrap.bundle.min.js' %}"></script>

      
  </body>
</html>

templates/signup/signup.html
{% load static %}
{% load crispy_forms_tags %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.83.1">
    <title>{{title}}</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/album/">

    

    <!-- Bootstrap core CSS -->
<link href="{% static 'assets/dist/css/bootstrap.min.css' %}" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    
  </head>
  <body>
    
<header>

<!-- new nav start -->
<div class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light rounded" aria-label="Eleventh navbar example">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Profile</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample09" aria-controls="navbarsExample09" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExample09">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'Albumapp:albumspage' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'sign_up_app:signup' %}">Sign-up</a>
            </li>


            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="dropdown09" data-bs-toggle="dropdown" aria-expanded="false">Touch us</a>
              <ul class="dropdown-menu" aria-labelledby="dropdown09">
                <li><a class="dropdown-item" href="#">Sign-up</a></li>
                <li><a class="dropdown-item" href="#">Sign-in</a></li>
                <li><a class="dropdown-item" href="#">About us</a></li>
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <div>

<!-- new nav end -->
  
<!-- defalt nav start
  
  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container">
      <a href="#" class="navbar-brand d-flex align-items-center">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2" viewBox="0 0 24 24"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg>
        <strong>Album</strong>
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
  defolt nav end -->
</header>

<main>

  <section class="py-6 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">Create New Account</h1>
      
      </div>
    </div>
  </section>

  <div class="album py-6 bg-light">
    <div class="container" style="padding-top:20px">


        {% if register %}
        <div class="alert alert-success">
          Account Creation Success
        </div>
        {% else %}
        <form class="form-control" id="formGroupExampleInput2" method="POST">
            <!-- new nav end -->
            {{ signup_form | crispy }}
            {% csrf_token %}
            <button type="submit" class="btn btn-success btn-sm" >Create Account</button>
            
        </form>
        <br>
        <p>Already Have Account? <a href="">let's login</a></p>
        {% endif %}
      </div>
    </div>
  </div>

</main>

<footer class="text-muted py-5">
  <div class="container">
    <p class="float-end mb-1">
      <a href="#">Back to top</a>
    </p>
    <p class="mb-1">Thanks to be here!!</p>
  </div>
</footer>


    <script src="{% static 'assets/dist/js/bootstrap.bundle.min.js' %}"></script>

      
  </body>
</html>